### ISSUE TITLE
希望做主编的贡献者来留一下名？

### ISSUE THREAD

**Issue by comradez** [Things-Before-Coding/early-suggestion#38]
仅仅是意见征集……

提醒一下，主编**可能**需要处理相当多的提案，所以请好好负起责任。

如果有的话也请把自己的优势简单讲一下，比如时间精力充足、有类似经验，当然单纯的热心也是很好的QAQ

**Comment by Hecate2** [comment]
留名！

**Comment by xiong35** [comment]
留名！  
完全自学，精通前端。会很多语言。有后端，爬虫，AI经验。近期时间不少。  
[简历](http://resume.xiong35.cn)，[个人网站](http://www.xiong35.cn)

**Comment by HeartyYF** [comment]
留名
清华在读，本学期内至下个学期开始前时间空余很多，预计下两个学期空闲时间较多

**Comment by zj713300** [comment]
留名
完全自学，ICPC学生教练，写过bot，对做教育方面有一些想法，工作日比较有空

**Comment by FLDPMpang** [comment]
留名
双非大一,退役OIer,学习FPGA与Soc设计,会爬虫与图像处理,网站搭建,linux开发
[个人博客](https://www.fldpmpang.website)

**Comment by LaoshuBaby** [comment]
留名
见过不少萌新（自己也是），*学过*C++，有忍受多个开源社区（中英皆有）邮件列表轰炸的经历（逃）
（因为技术觉得不够所以可能只算副主编？）

**Comment by comradez** [comment]
看上去应该不会有其他人来回复了。
一共六位热心人回复，我**确实**不清楚应该怎么选择。我的想法是有开源社区经验的人最为重要，然后就是时间充足，至于技术反而没那么重要（对于面向初学者的文章来说技术力太高甚至可能是负优化XD）。
那么我就动用一次硬点的权力了（笑）@Hecate2、@xiong35、@HeartyYF、@zj713300和@LaoshuBaby成为第一届主编，希望大家承担好这份责任，毕竟权力越大责任越大嘛QAQ 稍后我把权限赋给几位
@FLDPMpang 提到自己下学期时间比较充足，#13 中提到主编是有任期的，可以考虑时间比较充足的时候再参选？

**Comment by Akarinnnnn** [comment]
自学野路子，路径可供参考，用过几年C++ 17和C# 7.0+

我可以时不时来看一下，毕竟懒癌患者，assign可以找我
