### ISSUE TITLE
讲一下IDE应该怎么卸载，尤其是Visual Studio 2017+

### ISSUE THREAD

**Issue by Akarinnnnn** [Things-Before-Coding/early-suggestion#60]
我上次在维修部值班遇到一个不会卸VS2019，直接删文件，最后无奈重装系统的
我怕下次还有人出这事，干脆讲一下吧

**Comment by LaoshuBaby** [comment]
Duplicate with github.com/Things-Before-Coding/Things-Before-Coding-docs/issues/6

已收录至Windows系统的常见基本操作中，不建议单独作为编程语言相关话题

**Comment by Akarinnnnn** [comment]
请不要傲慢的以为VS 2017+的卸载方式和其他Windows软件一致
不同于其他IDE甚至是Windows软件，Visual Studio 2017需要在一开始的安装器中卸载，在控制面板中卸载的是安装器。

**Comment by Akarinnnnn** [comment]
重新打开，理由如上

**Comment by HeartyYF** [comment]
仍然可以归到 windows 使用入门里，因为在安装器里安装的不止 vs2017 一个，无论 unity hub 还是 cocos dashboard 都是如此；另外，我正在用的 vs2019 是可以通过控制面板直接卸载的，可以在内容中点出不同版本软件可能产生不同的行为。

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/118810964-0a013080-b8df-11eb-9627-cb5a969ff8cf.png)
![图片](https://user-images.githubusercontent.com/42690037/118811011-14bbc580-b8df-11eb-8779-a532877a360c.png)

以上来自仅安装了2017和仅安装了2019的两位用户的控制面板截图

确实此处是我没有料到的，也反映出我虽然忝列主编之一，但自己却不清楚一些常见使用细节（草，我安上就没考虑过卸载）

但就卸载软件这一点，VS系列IDE如果单独开一个专题，目前尚无足够显著性，且卸载这一行为应属于系统使用中的一个环节

就我的了解欠缺向诸位做出道歉

**Comment by ayaka14732** [comment]
@Akarinnnnn 看了你在这个 project 中的留言，想说请避免贬低其他人，特别是在其他 thread 里使用脏话。

你的观点也不一定合理，留言的语气却给人一种居高临下的感受，仿佛在教育其他 contributor，这无论是在开源社区还是在其他地方都不是合适的行为。

之前我给 Python 提 issue，里面有一句话语气不太好，结果被维护者指出，我很后悔，后来在开源社区就没那样说过话）

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn 看了你在这个 project 中的留言，想说请不要贬低其他人、特别是在其他 thread 里使用脏话的留言。
> 
> 你的观点也不一定合理，留言的语气却给人一种居高临下的感受，仿佛在教育其他 contributor，这无论是在开源社区还是在其他地方都称不上是合适的行为。
> 
> （之前我给 Python 提 issue，里面有一句话语气不太好，结果被维护者指出，我很后悔，后来在开源社区就没那样说过话，希望能与君共勉）

细说

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn At that time, I pointed out that it was _irresponsible_ to write ambiguous words in the document.
> The maintainer replied that I should not use such “derogatory words”.

If you are giving me advice, please do not use English unnecessarily, this is a Chinese community.
